In [4]:
import pandas as pd
import numpy as np

In [7]:
#Create a Numpy array
a = [[1,2], [3,4]]
np.array(a)

array([[1, 2],
       [3, 4]])

In [8]:
#Create a DataFrame
pd.DataFrame(a)

   0  1
0  1  2
1  3  4

In [20]:
#Labelled list (of python dictionaries)
df = pd.DataFrame([{"math": 1, "science": 2, "Name": "A"}, {"math": 3, "science": 4, "Name": "B"}])
df

   math  science Name
0     1        2    A
1     3        4    B

In [21]:
#Score of all students for math /// Math series
df["math"]

0    1
1    3
Name: math, dtype: int64

In [22]:
type(df["math"])  #This is a series

pandas.Series

In [23]:
type(df)          #This is a DataFrame. DataFrame is made up of series

pandas.DataFrame

In [24]:
#Know no. of rows and columns and more information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   math     2 non-null      int64
 1   science  2 non-null      int64
 2   Name     2 non-null      str
dtypes: int64(2), str(1)
memory usage: 180.0 bytes

In [26]:
df.head(1)      #To show top few entries of a DataFrame, by default top 5

   math  science Name
0     1        2    A

In [27]:
df.tail(1)      #To show bottom few entries of a DataFrame, by default bottom 5

   math  science Name
1     3        4    B