In [1]:
import pandas as pd

In [15]:
countries_covid_data = pd.read_csv("Covid-19/countries-aggregated.csv")    #to read a csv file

In [3]:
countries_covid_data.head()

         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0          0       0
1  2020-01-23  Afghanistan          0          0       0
2  2020-01-24  Afghanistan          0          0       0
3  2020-01-25  Afghanistan          0          0       0
4  2020-01-26  Afghanistan          0          0       0

In [4]:
countries_covid_data.tail()

              Date   Country  Confirmed  Recovered  Deaths
161563  2022-04-12  Zimbabwe     247094          0    5460
161564  2022-04-13  Zimbabwe     247160          0    5460
161565  2022-04-14  Zimbabwe     247208          0    5462
161566  2022-04-15  Zimbabwe     247237          0    5462
161567  2022-04-16  Zimbabwe     247237          0    5462

In [16]:
countries_covid_data.info()                   #get information of a dataset

<class 'pandas.DataFrame'>
RangeIndex: 161568 entries, 0 to 161567
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       161568 non-null  str
 1   Country    161568 non-null  str
 2   Confirmed  161568 non-null  int64
 3   Recovered  161568 non-null  int64
 4   Deaths     161568 non-null  int64
dtypes: int64(3), str(2)
memory usage: 6.2 MB

In [10]:
countries_covid_data["Date"] = pd.to_datetime(countries_covid_data["Date"])

In [17]:
countries_covid_data["Date"].nunique()       #get total count of unique values in a column

816

In [14]:
countries_covid_data["Country"].nunique()

198